# Copyright (c) Microsoft. All rights reserved. Licensed under the MIT license.
# See LICENSE in the project root for license information.

# Stock email (customized to signed in user's alias) to 
# send. Separated out for to not clutter up graph_service.py.
def get_email_text(alias):
	return "<html><head><meta http-equiv='Content-Type' content='text/html; charset=us-ascii'> <title></title></head><body style='font-family:calibri'><p>Congratulations " + alias + ",</p><p>This is a message from the Office 365 Connect sample. You are well on your way to incorporating Office 365 services in your apps.</p><h3>What&#8217;s next?</h3><ul><li>Check out <a href='http://graph.microsoft.io' target='_blank'>graph.microsoft.io</a> to start building apps with Microsoft Graph today with all the latest tools, templates, and guidance to get started quickly.</li><li>Head over to the <a href='https://graph.microsoft.io/en-us/docs' target='blank'>Microsoft Graph API documentation</a> to explore the rest of the APIs.</li><li>Browse other <a href='https://github.com/MicrosoftGraph/' target='_blank'>samples on GitHub</a> to see more of the APIs in action.</li></ul><h3>Give us feedback</h3> <ul><li>If you have any trouble running this sample, please <a href='http://github.com/OfficeDev/O365-Python-Microsoft-Graph-Connect/issues' target='_blank'>log an issue</a>.</li><li>For general questions about the Office 365 APIs, post to <a href='http://stackoverflow.com/' target='blank'>Stack Overflow</a>. Make sure that your questions or comments are tagged with [office365].</li></ul><p>Thanks and happy coding!<br>Your Office 365 Development team </p> <div style='text-align:center; font-family:calibri'> <table style='width:100%; font-family:calibri'> <tbody> <tr> <td><a href='http://github.com/OfficeDev/O365-Python-Microsoft-Graph-Connect'>See on GitHub</a> </td> <td><a href='http://officespdev.uservoice.com/'>Suggest on UserVoice</a> </td> <td><a href='http://twitter.com/share?text=I%20just%20started%20developing%20Python%20apps%20using%20the%20%23Office365%20Connect%20app!%20%40OfficeDev&url=http://github.com/OfficeDev/O365-Python-Microsoft-Graph-Connect'>Share on Twitter</a> </td> </tr> </tbody></table></div></body></html>"
	

	